from app.business.exceptions.vehiculo import VehiculoExistenteError, VehiculoNotFoundError
from app.business.exceptions.pedido import PedidoEstadoInvalidoError, PedidoNotFoundError, VentanaEntregaInvalidaError
from app.business.exceptions.asignacion import AsignacionNotFoundError, CapacidadInsuficienteError, PedidoYaAsignadoError, PedidoNoDisponibleError, VehiculoNoDisponibleError
from app.business.exceptions.ruta import RutaNotFoundError, RutaSinDatosError, RutaVehiculoInactivoError
